name: narrator-web

services:
  db:
    image: postgres:16-alpine
    ports:
    - "5432:5432"

  server:
    image: narrator-server
    build:
      context: .
      dockerfile: /apps/server/Dockerfile
    ports:
    - "3000:3000"
    depends_on:
      - db
  
  client:
    image: narrator-client
    build:
      context: .
      dockerfile: /apps/client/Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}